# Autogenerated wrapper script for LAPACK32_jll for aarch64-apple-darwin-libgfortran5
export liblapack32

using CompilerSupportLibraries_jll
using ReferenceBLAS32_jll
JLLWrappers.@generate_wrapper_header("LAPACK32")
JLLWrappers.@declare_library_product(liblapack32, "@rpath/liblapack32.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, ReferenceBLAS32_jll)
    JLLWrappers.@init_library_product(
        liblapack32,
        "lib/liblapack32.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
